services:
  postgres:
    container_name: postgres_todolistmanager
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todolistmanager
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  spring-app:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todomanagerapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todolistmanager
    
volumes:
  postgres: